[package]
name = "kfs"
version = "0.1.0"
edition = "2024"

[dependencies]

[lib]
name = "kfs"
path = "src/kmain.rs"
crate-type = ["staticlib"]
test=false

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"